"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

// Custom event dispatched to the player when the description or an external
// caller wants to seek to a specific timestamp. The player listens for this
// event on the document and calls remote.seek(seconds).
export const SEEK_EVENT = "cassette:seek";

export const dispatchSeek = (seconds: number): void => {
    document.dispatchEvent(new CustomEvent(SEEK_EVENT, { detail: { seconds } }));
};

// ---------------------------------------------------------------------------
// Player UI store — shared between the watch page and all player sub-components.
// ---------------------------------------------------------------------------

interface PlayerState {
    // Theatre mode: player spans full viewport width; sidebar + comments collapse.
    theatre: boolean;
    // Mini-player: player detaches to a corner card while browsing other pages.
    mini: boolean;

    toggleTheatre: () => void;
    setTheatre: (value: boolean) => void;
    toggleMini: () => void;
    setMini: (value: boolean) => void;
    // Programmatic seek — sets targetSeekSec; the player watches this and seeks
    // when it changes. Set to null after seeking to avoid re-triggering.
    targetSeekSec: number | null;
    seekTo: (seconds: number) => void;
    clearSeek: () => void;
    // Set of caption labels that are auto-generated (Whisper). Populated by
    // Player.tsx on mount so CaptionsMenu can render the AUTO badge without
    // needing the full VideoCaption[] array threaded through the prop chain.
    autoGeneratedCaptionLabels: ReadonlySet<string>;
    setAutoGeneratedCaptionLabels: (labels: ReadonlySet<string>) => void;
}

// `theatre` is the only field we persist across navigations / reloads — it's
// a user preference, not session state. Mini-player is also persisted so the
// detached tile survives an in-app navigation. Everything else (programmatic
// seek targets, ephemeral caption-label sets) is reset on every page-load.
export const usePlayerStore = create<PlayerState>()(
    persist(
        (set) => ({
            theatre: false,
            mini: false,
            targetSeekSec: null,
            autoGeneratedCaptionLabels: new Set(),

            toggleTheatre: () => set((s) => ({ theatre: !s.theatre })),
            setTheatre: (value) => set({ theatre: value }),
            toggleMini: () => set((s) => ({ mini: !s.mini })),
            setMini: (value) => set({ mini: value }),
            seekTo: (seconds) => set({ targetSeekSec: seconds }),
            clearSeek: () => set({ targetSeekSec: null }),
            setAutoGeneratedCaptionLabels: (labels) => set({ autoGeneratedCaptionLabels: labels }),
        }),
        {
            name: "cassette:player-ui",
            storage: createJSONStorage(() => localStorage),
            // Only persist the booleans — the seek/caption-label fields are
            // intentionally session-scoped.
            partialize: (state) => ({ theatre: state.theatre, mini: state.mini }),
        },
    ),
);
