#!/usr/bin/env bash
# scripts/restore.sh <backup-dir>
#
# Reverses scripts/backup.sh:
#   - drops + restores the database from db.sql.gz
#   - restores MEDIA_SOURCE_PATH and (optionally) MEDIA_HLS_PATH from the
#     tarballs alongside it
#
# Confirmation prompt is required; pass --yes to skip.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -f ".env" ]]; then
    set -a
    # shellcheck disable=SC1091
    . ./.env
    set +a
fi

DATABASE_URL="${DATABASE_URL:?DATABASE_URL is required}"
MEDIA_SOURCE_PATH="${MEDIA_SOURCE_PATH:-./media/source}"
MEDIA_HLS_PATH="${MEDIA_HLS_PATH:-./media/hls}"

backup_dir="${1:?usage: scripts/restore.sh <backup-dir> [--yes]}"
confirm="${2:-}"

if [[ ! -d "$backup_dir" ]]; then
    echo "[restore FAIL] not a directory: $backup_dir" >&2
    exit 1
fi

log() { printf "\033[36m[restore]\033[0m %s\n" "$*"; }

if [[ "$confirm" != "--yes" ]]; then
    echo "About to RESTORE $backup_dir into:"
    echo "  database: $(echo "$DATABASE_URL" | sed -E 's,([^:]+://[^:]+:)[^@]+(@.*),\1***\2,')"
    echo "  source:   $MEDIA_SOURCE_PATH"
    echo "  hls:      $MEDIA_HLS_PATH"
    echo "This will DROP and RECREATE all matching tables and overwrite the media dirs."
    read -rp "Type 'restore' to continue: " ack
    [[ "$ack" == "restore" ]] || { echo "aborted"; exit 1; }
fi

# ---------------------------------------------------------------------------
# 1. database
# ---------------------------------------------------------------------------
db_dump="$backup_dir/db.sql.gz"
if [[ -f "$db_dump" ]]; then
    log "psql restore from $db_dump"
    if command -v psql > /dev/null 2>&1; then
        # Drop the public schema first to make the restore idempotent.
        psql "$DATABASE_URL" -c "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public; DROP SCHEMA IF EXISTS pgboss CASCADE;"
        gunzip -c "$db_dump" | psql "$DATABASE_URL" -v ON_ERROR_STOP=1 > /dev/null
    elif docker compose ps db --status running > /dev/null 2>&1; then
        log "psql not on host; using `docker compose exec db psql`"
        docker compose exec -T db psql -U cassette -d cassette -c "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public; DROP SCHEMA IF EXISTS pgboss CASCADE;"
        gunzip -c "$db_dump" | docker compose exec -T db psql -U cassette -d cassette -v ON_ERROR_STOP=1 > /dev/null
    else
        echo "[restore FAIL] no psql on PATH and no `db` service running" >&2
        exit 1
    fi
else
    log "no db.sql.gz in backup; skipping database restore"
fi

# ---------------------------------------------------------------------------
# 2. source media
# ---------------------------------------------------------------------------
if [[ -f "$backup_dir/source.tar.gz" ]]; then
    log "extract source.tar.gz -> $(dirname "$MEDIA_SOURCE_PATH")"
    rm -rf "$MEDIA_SOURCE_PATH"
    mkdir -p "$(dirname "$MEDIA_SOURCE_PATH")"
    tar -C "$(dirname "$MEDIA_SOURCE_PATH")" -xzf "$backup_dir/source.tar.gz"
fi

# ---------------------------------------------------------------------------
# 3. HLS-derived (optional)
# ---------------------------------------------------------------------------
if [[ -f "$backup_dir/hls.tar.gz" ]]; then
    log "extract hls.tar.gz -> $(dirname "$MEDIA_HLS_PATH")"
    rm -rf "$MEDIA_HLS_PATH"
    mkdir -p "$(dirname "$MEDIA_HLS_PATH")"
    tar -C "$(dirname "$MEDIA_HLS_PATH")" -xzf "$backup_dir/hls.tar.gz"
else
    log "no hls.tar.gz in backup; HLS will need to be regenerated by re-running the transcode pipeline against the source files (or wait for the operator's cleanup pass)"
fi

log "done"
