"use client";

import { useMediaRemote, useMediaState, useCaptionOptions, useMediaPlayer } from "@vidstack/react";
import { Subtitles } from "lucide-react";
import { useEffect, useState } from "react";

import { cn } from "@/lib/utils";
import { usePlayerStore } from "@/lib/player/store";

/**
 * Captions language picker with an on/off toggle.
 * Uses Vidstack's useCaptionOptions to get the available caption tracks.
 * Renders a small "AUTO" badge next to tracks where isAutoGenerated is true.
 * Auto-generated track labels are supplied via the player store (seeded by Player.tsx).
 */
export const CaptionsMenu = () => {
    const autoGeneratedCaptionLabels = usePlayerStore((s) => s.autoGeneratedCaptionLabels);
    const [open, setOpen] = useState(false);
    const options = useCaptionOptions();
    const remote = useMediaRemote();
    const player = useMediaPlayer();
    const textTrack = useMediaState("textTrack");

    const isOn = textTrack !== null;

    // Mirror SettingsMenu: dismiss on pointer leaving the player surface and
    // on Escape (TV remote "Back" maps to Escape on most devices).
    useEffect(() => {
        const onLeave = () => setOpen(false);
        window.addEventListener("cassette:player-leave", onLeave);
        return () => window.removeEventListener("cassette:player-leave", onLeave);
    }, []);
    useEffect(() => {
        if (!open) return;
        const onKey = (e: KeyboardEvent) => {
            if (e.key === "Escape") {
                e.stopPropagation();
                setOpen(false);
            }
        };
        document.addEventListener("keydown", onKey);
        return () => document.removeEventListener("keydown", onKey);
    }, [open]);

    // Vidstack's useCaptionOptions includes a synthetic "Off" entry even on
    // tracks-less videos — so options.length is never 0 in practice. Filter
    // it out so we both hide the button when no real tracks exist AND don't
    // render a duplicate "Off Off" inside the popover (we render our own
    // Off row).
    const realOptions = options.filter((o) => o.label.toLowerCase() !== "off");
    if (realOptions.length === 0) return null;

    return (
        <div className="relative">
            <button
                aria-label="Captions"
                aria-expanded={open}
                aria-pressed={isOn}
                onClick={() => setOpen((v) => !v)}
                className={cn(
                    "flex h-9 w-9 items-center justify-center rounded-full",
                    "hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/60",
                    "transition-colors",
                    isOn ? "text-white" : "text-white/50",
                    open && "bg-white/10",
                )}
            >
                <Subtitles
                    size={20}
                    strokeWidth={2.25}
                    fill={isOn ? "currentColor" : "none"}
                    fillOpacity={isOn ? 0.15 : 0}
                />
            </button>

            {open && (
                <>
                    <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
                    <div
                        className="player-popover absolute bottom-full right-0 z-50 mb-2 w-44 overflow-hidden rounded-xl py-2"
                        onClick={(e) => e.stopPropagation()}
                    >
                        {/* Off option */}
                        <button
                            className={cn(
                                "flex w-full items-center justify-between px-4 py-2 text-sm",
                                "transition-colors hover:bg-white/10",
                                !isOn ? "font-medium text-white" : "text-white/70",
                            )}
                            onClick={() => {
                                // Disable all caption tracks by setting mode to 'disabled'.
                                const tracks = player?.textTracks;
                                if (tracks) {
                                    for (let i = 0; i < tracks.length; i++) {
                                        const t = tracks[i];
                                        if (t && (t.kind === "subtitles" || t.kind === "captions")) {
                                            remote.changeTextTrackMode(i, "disabled");
                                        }
                                    }
                                }
                                setOpen(false);
                            }}
                        >
                            <span>Off</span>
                            {!isOn && <Check />}
                        </button>

                        {realOptions.map((opt) => {
                            const isAuto = autoGeneratedCaptionLabels.has(opt.label);
                            return (
                                <button
                                    key={opt.label}
                                    className={cn(
                                        "flex w-full items-center justify-between px-4 py-2 text-sm",
                                        "transition-colors hover:bg-white/10",
                                        opt.selected ? "font-medium text-white" : "text-white/70",
                                    )}
                                    onClick={() => {
                                        opt.select();
                                        setOpen(false);
                                    }}
                                >
                                    <span className="flex items-center gap-1.5">
                                        {opt.label}
                                        {isAuto && (
                                            <span className="rounded bg-white/15 px-1 py-px text-[10px] font-semibold leading-none tracking-wide text-white/80">
                                                AUTO
                                            </span>
                                        )}
                                    </span>
                                    {opt.selected && isOn && <Check />}
                                </button>
                            );
                        })}
                    </div>
                </>
            )}
        </div>
    );
};

const Check = () => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
        <path
            d="M2 7l3.5 3.5L12 3"
            stroke="currentColor"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
        />
    </svg>
);
