"use client";

import {
    Captions,
    MediaPlayer,
    MediaProvider,
    Track,
    useMediaPlayer,
    useMediaRemote,
    useMediaState,
} from "@vidstack/react";
import { useEffect, useRef, useState } from "react";
import { Volume2 } from "lucide-react";

import { SEEK_EVENT, usePlayerStore } from "@/lib/player/store";
import { readPreferences, writeVolume, writePlaybackRate, writeStatsOverlayEnabled } from "@/lib/player/preferences";
import type { Video, VideoCaption, VideoChapter, VideoVariant } from "@/server/db/schema/videos";
import { PlayerCanvas } from "./PlayerCanvas";
import { PlayerContextMenu } from "./PlayerContextMenu";
import { PlayerVignette } from "./PlayerVignette";
import { PlayerTopBar } from "./PlayerTopBar";
import { PlayerCenterStage } from "./PlayerCenterStage";
import { PlayerBottomBar } from "./PlayerBottomBar";
import { UpNextOverlay } from "./UpNextOverlay";
import { KeyboardShortcutsOverlay, useShortcutsOverlay } from "./KeyboardShortcutsOverlay";
import { useWatchBeacon, sendPauseBeacon } from "./useWatchBeacon";
import { useIdleControls } from "./useIdleControls";
import { useMediaSession } from "./useMediaSession";

interface NextVideo {
    id: string;
    title: string;
    thumbnailPath: string | null;
    channel: { name: string; handle: string };
    durationSec: number | null;
}

interface PlayerProps {
    video: Video;
    captions: VideoCaption[];
    chapters: VideoChapter[];
    variants: VideoVariant[];
    signedToken: string | null;
    // Next video in the queue or channel — used by UpNextOverlay.
    queueNext: NextVideo | null;
    channel: {
        id: string;
        handle: string;
        name: string;
        avatarPath: string | null;
    };
    // Embed customisation — all optional; defaults are the standard watch-page behaviour.
    autoplay?: boolean;
    muted?: boolean;
    loop?: boolean;
    /** "hidden" hides all player chrome (top bar, centre stage, bottom bar). */
    controls?: "auto" | "hidden";
    /** Start playback from this second on initial load. */
    startSec?: number;
}

/**
 * Vidstack headless player with Apple-TV-style custom layout.
 *
 * Keyboard shortcuts wired via event listeners on the document:
 *   Space / K — play/pause
 *   J / L     — ±10 s
 *   ← / →     — ±5 s
 *   0-9        — seek to N×10%
 *   M          — mute
 *   ↑ / ↓     — volume ±10%
 *   F          — fullscreen
 *   T          — theatre
 *   C          — captions
 *   > / <      — speed +/-0.25
 */
export const Player = ({
    video,
    captions,
    chapters,
    variants,
    signedToken,
    queueNext,
    channel,
    autoplay = false,
    muted = false,
    loop = false,
    controls = "auto",
    startSec,
}: PlayerProps) => {
    const tokenQS = signedToken ? `?t=${signedToken}` : "";
    const setAutoGeneratedCaptionLabels = usePlayerStore((s) => s.setAutoGeneratedCaptionLabels);

    // Seed the store so CaptionsMenu can show the AUTO badge without prop-drilling.
    const autoLabels = new Set(captions.filter((c) => c.isAutoGenerated).map((c) => c.label));
    setAutoGeneratedCaptionLabels(autoLabels);

    // Read stored captions preference once on render (SSR-safe).
    const storedCaptionsLang = typeof window !== "undefined" ? readPreferences().captionsLang : null;

    return (
        <MediaPlayer
            className="relative w-full overflow-hidden bg-black"
            style={{ aspectRatio: "16/9" }}
            src={`/api/hls/${video.id}/master.m3u8${tokenQS}`}
            crossOrigin
            playsInline
            streamType="on-demand"
            load="eager"
            autoPlay={autoplay}
            muted={muted}
            loop={loop}
            currentTime={startSec}
            keyShortcuts={{
                togglePaused: ["Space", "k"],
                seekBackward: "j",
                seekForward: "l",
                seekBackward5: "ArrowLeft",
                seekForward5: "ArrowRight",
                toggleMuted: "m",
                toggleFullscreen: "f",
                toggleCaptions: "c",
                volumeUp: "ArrowUp",
                volumeDown: "ArrowDown",
            }}
        >
            <MediaProvider>
                {/* Sprite VTT for scrubber thumbnail previews */}
                <Track src={`/api/hls/${video.id}/thumb/sprite.vtt`} kind="metadata" default label="thumbnails" />
                {/* Caption tracks — prefer stored language preference over DB isDefault flag. */}
                {captions.map((c) => (
                    <Track
                        key={c.lang}
                        src={`/api/hls/${video.id}/captions/${c.lang}.vtt${tokenQS}`}
                        kind="subtitles"
                        lang={c.lang}
                        label={c.label}
                        default={storedCaptionsLang !== null ? c.lang === storedCaptionsLang : c.isDefault}
                    />
                ))}
            </MediaProvider>

            {/* Rendered captions overlay */}
            <Captions className="absolute bottom-16 left-4 right-4 z-50 text-center" />

            <PlayerInner
                video={video}
                chapters={chapters}
                variants={variants}
                queueNext={queueNext}
                channel={channel}
                tokenQS={tokenQS}
                controls={controls}
                autoplay={autoplay}
                muted={muted}
            />
        </MediaPlayer>
    );
};

// Inner component so we can use Vidstack hooks (which require MediaPlayer as ancestor).
const PlayerInner = ({
    video,
    chapters,
    variants,
    queueNext,
    channel,
    controls = "auto",
    autoplay = false,
    muted = false,
    // tokenQS reserved for future use (e.g. authenticating beacon requests)
    tokenQS: _tokenQS,
}: Omit<PlayerProps, "captions" | "signedToken" | "loop" | "startSec"> & {
    tokenQS: string;
    controls?: "auto" | "hidden";
}) => {
    const remote = useMediaRemote();
    const player = useMediaPlayer();
    const paused = useMediaState("paused");
    const playerMuted = useMediaState("muted");
    const { active } = useIdleControls(paused);

    // Tap-to-unmute affordance — visible when the player started muted due to
    // autoplay policy and the user has not yet unmuted. Hides on any
    // interaction.
    const [showUnmuteHint, setShowUnmuteHint] = useState(autoplay && muted);
    const toggleTheatre = usePlayerStore((s) => s.toggleTheatre);
    const targetSeekSec = usePlayerStore((s) => s.targetSeekSec);
    const clearSeek = usePlayerStore((s) => s.clearSeek);
    const { open: shortcutsOpen, setOpen: setShortcutsOpen } = useShortcutsOverlay();

    // Restore volume and playback rate from localStorage once the player is ready.
    useEffect(() => {
        if (!player) return;
        const prefs = readPreferences();

        const unsubscribe = player.subscribe(({ canPlay }) => {
            if (!canPlay) return;
            remote.changeVolume(prefs.volume);
            remote.changePlaybackRate(prefs.playbackRate);
            unsubscribe();
        });

        return unsubscribe;
    }, [player, remote]);

    // Autoplay race fix.  Vidstack's `autoPlay` prop attempts play() before
    // hls.js has attached the MediaSource on some browser+codec combos; the
    // attempt silently no-ops and the video sits at frame zero.  Wait for
    // canPlay, then call play() ourselves.  Idempotent: if Vidstack already
    // started playback, this is a no-op (play() on a playing element resolves).
    useEffect(() => {
        if (!player || !autoplay) return;
        let attempted = false;
        const unsubscribe = player.subscribe(({ canPlay, paused: isPaused }) => {
            if (!canPlay || attempted) return;
            if (!isPaused) {
                // Already playing — nothing to do.
                attempted = true;
                unsubscribe();
                return;
            }
            attempted = true;
            // Browsers reject unmuted autoplay; fall back to muted on rejection
            // so playback always starts.  The tap-to-unmute affordance covers the rest.
            const tryPlay = async () => {
                try {
                    await player.play();
                } catch {
                    try {
                        player.muted = true;
                        await player.play();
                    } catch {
                        /* user-gesture-required — leave paused, user clicks centre stage */
                    }
                }
            };
            void tryPlay();
            unsubscribe();
        });
        return unsubscribe;
    }, [player, autoplay]);

    // Hide the unmute hint as soon as the player is unmuted (any path: keyboard
    // shortcut, volume slider, context-menu unmute).
    useEffect(() => {
        if (!playerMuted && showUnmuteHint) setShowUnmuteHint(false);
    }, [playerMuted, showUnmuteHint]);

    // Persist volume changes (debounced inside writeVolume).
    useEffect(() => {
        if (!player) return;
        return player.subscribe(({ volume }) => {
            writeVolume(volume);
        });
    }, [player]);

    // Persist playback rate changes (debounced).
    useEffect(() => {
        if (!player) return;
        return player.subscribe(({ playbackRate }) => {
            writePlaybackRate(playbackRate);
        });
    }, [player]);

    // Apply programmatic seeks from the store (e.g., description timestamp clicks).
    useEffect(() => {
        if (targetSeekSec !== null) {
            remote.seek(targetSeekSec);
            clearSeek();
        }
    }, [targetSeekSec, remote, clearSeek]);

    // Also listen for the custom DOM event (description component dispatches this).
    useEffect(() => {
        const handler = (e: Event) => {
            const detail = (e as CustomEvent<{ seconds: number }>).detail;
            if (typeof detail?.seconds === "number") {
                remote.seek(detail.seconds);
            }
        };
        document.addEventListener(SEEK_EVENT, handler);
        return () => document.removeEventListener(SEEK_EVENT, handler);
    }, [remote]);

    // Speed shortcuts: > and < (not in Vidstack's built-in key shortcut map).
    // Also handles T (theatre), I (PiP), 0-9 (% seek), and ? (shortcuts overlay).
    useEffect(() => {
        const onKey = (e: KeyboardEvent) => {
            const tag = (e.target as HTMLElement)?.tagName;
            if (tag === "INPUT" || tag === "TEXTAREA") return;
            if (e.key === "?" || (e.key === "/" && e.shiftKey)) {
                setShortcutsOpen((v) => !v);
            } else if (e.key === ">" || (e.key === "." && e.shiftKey)) {
                const currentRate = player?.state.playbackRate ?? 1;
                remote.changePlaybackRate(Math.min(2, currentRate + 0.25));
            } else if (e.key === "<" || (e.key === "," && e.shiftKey)) {
                const currentRate = player?.state.playbackRate ?? 1;
                remote.changePlaybackRate(Math.max(0.25, currentRate - 0.25));
            } else if (e.key === "b" || e.key === "B") {
                // Toggle stats overlay — dispatch a custom event that SettingsMenu picks up.
                const current = readPreferences().statsOverlayEnabled;
                writeStatsOverlayEnabled(!current);
                window.dispatchEvent(new CustomEvent("cassette:stats-toggle", { detail: { enabled: !current } }));
            } else if (e.key === "t" || e.key === "T") {
                toggleTheatre();
            } else if (e.key === "i" || e.key === "I") {
                void remote.enterPictureInPicture();
            } else if (e.key.match(/^[0-9]$/)) {
                const pct = Number(e.key) / 10;
                const dur = player?.state.duration ?? 0;
                if (dur > 0) remote.seek(pct * dur);
            }
        };
        document.addEventListener("keydown", onKey);
        return () => document.removeEventListener("keydown", onKey);
    }, [remote, player, toggleTheatre, setShortcutsOpen]);

    // Broadcast current playback position as a DOM event so external components
    // (e.g. TranscriptSidebar) can highlight the active cue without coupling
    // to Vidstack internals.  Throttled to 250 ms to keep DOM event volume low.
    useEffect(() => {
        if (!player) return;
        let lastEmitMs = 0;
        return player.subscribe(({ currentTime }) => {
            const nowMs = Date.now();
            if (nowMs - lastEmitMs < 250) return;
            lastEmitMs = nowMs;
            window.dispatchEvent(new CustomEvent("cassette:position", { detail: { seconds: currentTime } }));
        });
    }, [player]);

    // Watch progress beacon wiring.
    const getPositionSec = () => player?.state.currentTime ?? 0;
    const seek = (seconds: number) => remote.seek(seconds);

    useWatchBeacon({ videoId: video.id, getPositionSec, seek });

    // Wire the W3C Media Session so OS lockscreen / MPRIS / Now Playing
    // surfaces show metadata and accept play/pause/seek/prev/next.
    useMediaSession({
        player,
        video: { id: video.id, title: video.title, thumbnailPath: video.thumbnailPath },
        channel: { name: channel.name },
        queue: { next: queueNext ? { id: queueNext.id } : null, prev: null },
    });

    // Pause beacon.
    const handlePause = () => {
        sendPauseBeacon(video.id, getPositionSec());
    };

    return (
        <>
            {/* Pause beacon handler */}
            <PauseHandler onPause={handlePause} />

            {/* Keyboard shortcuts help dialog */}
            <KeyboardShortcutsOverlay open={shortcutsOpen} onOpenChange={setShortcutsOpen} />

            <PlayerCanvas>
                {controls !== "hidden" && <PlayerVignette />}

                {controls !== "hidden" && (
                    <PlayerTopBar
                        title={video.title}
                        channelId={channel.id}
                        channelName={channel.name}
                        channelHandle={channel.handle}
                        avatarPath={channel.avatarPath}
                        active={active}
                    />
                )}

                {controls !== "hidden" && <PlayerCenterStage />}

                {controls !== "hidden" && (
                    <PlayerBottomBar videoId={video.id} chapters={chapters} variants={variants} active={active} />
                )}

                <UpNextOverlay next={queueNext} />

                {/* Tap-to-unmute affordance.  Visible only while the player is
                    still muted *and* the user has not yet interacted; one click
                    anywhere unmutes and dismisses. */}
                {showUnmuteHint && playerMuted && (
                    <button
                        type="button"
                        aria-label="Tap to unmute"
                        onClick={() => {
                            remote.unmute();
                            setShowUnmuteHint(false);
                        }}
                        className="surface-glass pointer-events-auto absolute left-4 top-4 z-40 flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-medium text-white shadow-lg ring-1 ring-white/15 transition-all hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/60"
                    >
                        <Volume2 size={14} strokeWidth={2.25} />
                        <span>Tap to unmute</span>
                    </button>
                )}
            </PlayerCanvas>

            {/* Custom right-click context menu — rendered outside the canvas
                so it can position itself in viewport coordinates. */}
            {controls !== "hidden" && <PlayerContextMenu videoId={video.id} />}
        </>
    );
};

// Tiny component that hooks up the pause event handler.
const PauseHandler = ({ onPause }: { onPause: () => void }) => {
    const paused = useMediaState("paused");
    const hasStarted = useRef(false);

    useEffect(() => {
        if (!paused && !hasStarted.current) {
            hasStarted.current = true;
        }
        if (paused && hasStarted.current) {
            onPause();
        }
    }, [paused, onPause]);

    return null;
};
